# This is a basic workflow to help you get started with Actions

name: terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#  push:
#    branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ecr-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: git checkout

      - uses: actions/get-aws-credentials@v1
        with:
          ROLE_ARN: ${{secrets.GithubActionRole}}
          ROLE_SESSION_NAME: ecrsessionrole
          REGION: "us-west-2"
        
      - name: print assume role
        run: aws sts get-caller-identity
      

      # Runs a single command using the runners shell
      - name: Get Aws Credentials
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          terraform init
          terraform plan -out=tfplan


