on:
  workflow_dispatch:
      inputs:
        s3bucketname:
              type: string
              description: s3 name
              required: true
        # s3bucketname:
        #       type: string
        #       description: Enter Env  name
        #       required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  id-token: write
  contents: read
jobs:
  # This workflow contains a single job called "build"
  s3-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        name: git checkout

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        

      - uses: aws-actions/configure-aws-credentials@v2
        name: Configure AWS role
        with:
          aws-region: us-west-2
          role-to-assume: "arn:aws:iam::156416945165:role/GithubActionRole"
          role-session-name: GitHubActions

        
      - name: print assume role
        run: aws sts get-caller-identity
      

      # Runs a single command using the runners shell
      # - name: Get Aws Credentials
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:
          terraform init -backend-config="bucket=terraformtfstatebucket01" -backend-config="key=${{ input.s3_bucketname }}/terraform"/${{ inputs.s3_bucketname }}" -reconfigure
          terraform plan -out=tfplan -var "s3_bucketname=${{ inputs.s3_bucketname }}" -var-file="$prod.tfvars"
          terraform apply "tfplan"


          